# Generated by Django 3.1.7 on 2021-05-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='visit_duration_time',
            field=models.IntegerField(null=True),
        ),
    ]
