# Generated by Django 3.1.7 on 2021-05-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rate'),
        ('users', '0002_doctor_visit_duration_time'),
    ]

    operations = [
    ]
