# Generated by Django 3.1.7 on 2021-04-09 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210406_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_of_specialization', models.CharField(choices=[('C', 'Cardiologist'), ('D', 'Dermatologist'), ('G', 'General practitioner'), ('GY', 'Gynecologist'), ('I', 'Internist'), ('N', 'Neurologist'), ('O', 'Obstetrician'), ('OP', 'Ophthalmologist'), ('OT', 'Otolaryngologist'), ('P', 'Pediatrician '), ('PS', 'Psychiatrist '), ('U', 'Urologist')], default='G', max_length=255)),
                ('gmc_number', models.IntegerField()),
                ('work_experience', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
