# Generated by Django 3.1.7 on 2021-04-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210409_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='pro_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
