# Generated by Django 3.1.7 on 2021-05-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='phone',
        ),
    ]
