# Generated by Django 3.1.7 on 2021-05-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_office_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField()),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.office')),
            ],
        ),
        migrations.DeleteModel(
            name='phone',
        ),
    ]
