# Generated by Django 3.1.7 on 2021-04-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='dr',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='ur',
            new_name='user_id',
        ),
    ]
