# Generated by Django 3.1.7 on 2021-05-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210525_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='titlte',
            new_name='title',
        ),
    ]
