# Generated by Django 3.1.7 on 2021-05-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210526_0012'),
        ('users', '0003_merge_20210517_2003'),
    ]

    operations = [
    ]
