# Generated by Django 3.1.7 on 2021-06-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210602_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='amount',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
