# Generated by Django 3.1.7 on 2021-06-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210530_2237'),
        ('users', '0010_auto_20210602_2257'),
    ]

    operations = [
    ]
