# Generated by Django 3.1.7 on 2021-06-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20210612_1847'),
        ('users', '0011_merge_20210615_1149'),
    ]

    operations = [
    ]
