# Generated by Django 3.1.7 on 2021-07-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20210615_1948'),
        ('users', '0012_merge_20210616_1731'),
    ]

    operations = [
    ]
