# Generated by Django 3.1.7 on 2021-07-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20210705_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_confirmed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
