# Generated by Django 3.1.7 on 2021-06-16 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 13, 6, 57, 317633, tzinfo=utc)),
        ),
    ]
