# Generated by Django 3.1.7 on 2021-06-16 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20210616_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 13, 8, 50, 206800, tzinfo=utc)),
        ),
    ]
